version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install pipx
      - pipx install poetry
      - pipx upgrade poetry
      - poetry install

sphinx:
  configuration: docs/source/conf.py
