name: Coveralls

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Python 3.10
      uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10'

    - name: Setup Poetry
      run: |
        pip install --upgrade pip
        pip install pipx
        pipx install poetry
        pipx upgrade poetry

    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Install
      run: poetry install

    - name: Run Tests
      run: poetry run tests --coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
